version: "3.8"

services:
  user-db:
    image: mysql:oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - user-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  user-db:
